#!/bin/sh
# X-TufAioControl-Managed: true
set -eu

data_home=${XDG_DATA_HOME:-"${HOME:?HOME is required}/.local/share"}
case "$data_home" in /*) ;; *) data_home="$HOME/.local/share" ;; esac
application="$data_home/tuf-aio-control/app/tuf_aio_gui.py"

if [ ! -r "$application" ]; then
    printf 'TUF AIO Control installation is incomplete: %s\n' "$application" >&2
    exit 1
fi

exec /usr/bin/python3 -B "$application" "$@"
